user_input= input("Enter a list of numbers seperated by spaces: ")
input_list= user_input.split()
numbers= list(map(int,input_list))
total= sum(numbers)
length = len(numbers)
sorted_numbers = sorted(numbers)
print(f"original list of numbers: {numbers}")
print(f"sum of numbers: {total}")
print(f" number of elements: {length}")
print(f"sorted list of numbers: {sorted_numbers}")
